version: "3.8"

services:
  #  bob-works-db:
  #    container_name: bob-works-db
  #    image: postgres
  #    privileged: true
  #    ports:
  #      - "15432:5432"
  #    environment:
  #      POSTGRES_PASSWORD: 12345
  #      PGDATA: /var/lib/postgresql/data/pgdata
  #    networks:
  #      - bob-works-network
  #    volumes:
  #      - ./postgres/data:/var/lib/postgresql/data/pgdata
  bob-works-config-service:
    container_name: bob-works-config-service
    image: ghcr.io/bob-park/bob-works-back-end/bob-works-config-service
    privileged: true
    build:
      context: ./bob-works-config-service
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      logs_level: debug
      logs_path: /root/app/logs
      config_path: /root/config
    ports:
      - "8888:8888"
    networks:
      - bob-works-network
    volumes:
      - ./bob-works-config-service:/root/app
      - ./config:/root/config
  bob-works-discovery-service:
    container_name: bob-works-discovery-service
    image: ghcr.io/bob-park/bob-works-back-end/bob-works-discovery-service
    privileged: true
    build:
      context: ./bob-works-discovery-service
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      logs_level: debug
      logs_path: /root/app/logs
      config_server_url: http://bob-works-config-service:8888
    ports:
      - "8761:8761"
    networks:
      - bob-works-network
    volumes:
      - ./bob-works-discovery-service:/root/app
    depends_on:
      bob-works-config-service:
        condition: service_healthy
  bob-works-authorization-service:
    container_name: bob-works-authorization-service
    image: ghcr.io/bob-park/bob-works-back-end/bob-works-authorization-service
    privileged: true
    build:
      context: ./bob-works-authorization-service
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      logs_level: debug
      logs_path: /root/app/logs
      config_server_url: http://bob-works-config-service:8888
    ports:
      - "9000:9000"
    networks:
      - bob-works-network
    volumes:
      - ./bob-works-authorization-service:/root/app
    depends_on:
      bob-works-discovery-service:
        condition: service_healthy
  bob-works-user-service:
    container_name: bob-works-user-service
    image: ghcr.io/bob-park/bob-works-back-end/bob-works-user-service
    privileged: true
    build:
      context: ./bob-works-user-service
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      logs_level: debug
      logs_path: /root/app/logs
      config_server_url: http://bob-works-config-service:8888
    ports:
      - "8081:8080"
    networks:
      - bob-works-network
    volumes:
      - ./bob-works-user-service:/root/app
    depends_on:
      bob-works-authorization-service:
        condition: service_healthy
  bob-works-document-service:
    container_name: bob-works-document-service
    image: ghcr.io/bob-park/bob-works-back-end/bob-works-document-service
    privileged: true
    build:
      context: ./bob-works-document-service
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      logs_level: debug
      logs_path: /root/app/logs
      config_server_url: http://bob-works-config-service:8888
    ports:
      - "8082:8080"
    networks:
      - bob-works-network
    volumes:
      - ./bob-works-document-service:/root/app
    depends_on:
      bob-works-authorization-service:
        condition: service_healthy
  bob-works-client-service:
    container_name: bob-works-client-service
    image: ghcr.io/bob-park/bob-works-back-end/bob-works-client-service
    privileged: true
    build:
      context: ./bob-works-client-service
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      logs_level: debug
      logs_path: /root/app/logs
      config_server_url: http://bob-works-config-service:8888
    ports:
      - "8083:8080"
    networks:
      - bob-works-network
    volumes:
      - ./bob-works-client-service:/root/app
    depends_on:
      bob-works-authorization-service:
        condition: service_healthy
  bob-works-notice-service:
    container_name: bob-works-notice-service
    image: ghcr.io/bob-park/bob-works-back-end/bob-works-notice-service
    privileged: true
    build:
      context: ./bob-works-notice-service
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      logs_level: debug
      logs_path: /root/app/logs
      config_server_url: http://bob-works-config-service:8888
    ports:
      - "8084:8080"
    networks:
      - bob-works-network
    volumes:
      - ./bob-works-client-service:/root/app
    depends_on:
      bob-works-authorization-service:
        condition: service_healthy
  bob-works-maintenance-service:
    container_name: bob-works-maintenance-service
    image: ghcr.io/bob-park/bob-works-back-end/bob-works-maintenance-service
    privileged: true
    build:
      context: ./bob-works-maintenance-service
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      logs_level: debug
      logs_path: /root/app/logs
      config_server_url: http://bob-works-config-service:8888
    ports:
      - "8085:8080"
    networks:
      - bob-works-network
    volumes:
      - ./bob-works-maintenance-service:/root/app
    depends_on:
      bob-works-authorization-service:
        condition: service_healthy

networks:
  bob-works-network:
    name: bob-works-network